title: EnriqueRDL
description: EnriqueRDL's website

sass:
    style: compressed

permalink: /blog/:title/

baseurl: https://enriquerdl.com # http://127.0.0.1:5500/_site

twitter: https://twitter.com/EnriqueRDL
github: https://github.com/EnriqueRDL

markdown: kramdown

collections:
    authors:
    portfolio:
        output: true
        permalink: /portfolio/:title/
    secret:
        output: true
        permalink: /secret/:title/


defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            author: "EnriqueRDL"
    -
        scope:
            path: ""
            type: "portfolio"
        values:
            layout: "portfolio"
    -
        scope:
            path: ""
            type: "secret"
        values:
            layout: "default"