title: EnriqueRDL
description: EnriqueRDL's website

sass:
    style: compressed

permalink: /blog/:title/

baseurl: /jekylltest/_site

twitter: https://twitter.com/EnriqueRDL
github: https://github.com/EnriqueRDL

markdown: kramdown

collections:
    authors:

defaults:
  -
    scope:
        path: ""
        type: "pages"
    values:
        layout: "default.html"
  -
    scope:
        path: ""
        type: "posts" # previously `page` in Jekyll 2.2.
    values:
        layout: "post" # overrides previous default layout
        author: "EnriqueRDL"