title: EnriqueRDL
url: https://enriquerdl.com # https://enriquerdl.com # http://localhost:4000
description: EnriqueRDL creates professional Shopify and WordPress websites. Get the web design and development services you need today!
tagline: Creating professional Shopify and WordPress websites.

assetversions:
    css: 1.0.4

css:
    production: true
    version: 1.0.5
    files:
        - reset.scss
        - default.scss
        - toc.scss

js:
    production: false
    version: 1.0.5
    files:
        - archive-search.js
        - toc.js

exclude: [
    readme.md
]

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

sass:
    style: compressed

permalink: /blog/:title/

email: enrique@enriquerdl.com
twitter:
    username: enriquerdl
    card: summary_large_image
github: https://github.com/EnriqueRDL


markdown: kramdown

defaults:
    -
        scope:
            path: ""
            type: pages
        values:
            layout: default
            image:
                path: /assets/images/site_image.jpg
                width: 1200
                height: 1200
                alt: a screenshot of the enriquerdl homepage
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
            archivetype: "blog posts"
            image:
                path: /assets/images/site_image.jpg
                width: 1200
                height: 1200
                alt: a screenshot of the enriquerdl homepage
            author:
                name: EnriqueRDL
                url: https://enriquerdl.com/
            toc: true